cloud:
  aws:
    region:
      static: us-east-2
    stack:
      auto: false                 
    credentials:                      
      access-key: 
      secret-key:     
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
                        
## NOTA: Se quito el acces-key y el secret-key, debido a restricciones de AWS y GitHub