cloud:
  aws:
    region:
      static: us-east-2
    stack:
      auto: false                 
    credentials:                      
      access-key: AKIA4KZBE5Z7R76QLA6X
      secret-key: 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            
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
                        
